version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6
  
jobs:
  build-and-test:
    working_directory: ~/test-repository/Backend/ftn
    docker:
      - image: cimg/openjdk:11.0
      - image: circleci/postgres:9.6.2-alpine
        auth:
          username: jelovceva
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: fishing-booker          

    steps:
      - checkout:
          path: ~/test-repository
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test

workflows:
  build-test-deploy:
    jobs:
      - build-and-test
      - heroku/deploy-via-git:
          name: deploy-back
          app-name: fishing-booker-back
          filters:
            branches:
              only:
                - main
          requires:
            - build-and-test
      - heroku/deploy-via-git:
          name: deploy-front
          app-name: fishing-booker-front
          filters:
            branches:
              only:
                - main
          requires:
            - deploy-back